apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: suu-kafka
  labels:
    app: kafka-client
spec:
  restartPolicy: Never
  containers:
    - name: kafka-client
      image: quay.io/strimzi/kafka:1.0.0-kafka-4.2.0
      command: ["sleep", "infinity"]
